"""add_password_field

Revision ID: 5f9e43bfebfd
Revises: b1e6ed026a66
Create Date: 2024-12-19 19:33:34.412203

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f9e43bfebfd"
down_revision = "b1e6ed026a66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###
